language: csharp
solution: MCProject.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore MCProject.sln
after_script:
  - nunit-console bin/Release//MCRoute.Test.dll
