// <auto-generated />
using System;
using McWorld.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McWorld.Shared.Migrations
{
    [DbContext(typeof(McDbContext))]
    partial class McDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("McWorld.Shared.Models.Event", b =>
                {
                    b.Property<Guid>("EventID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EndDate")
                        .IsRequired();

                    b.Property<string>("EndTime")
                        .IsRequired();

                    b.Property<string>("Headline")
                        .IsRequired();

                    b.Property<int>("RegistrationCount");

                    b.Property<Guid>("RouteID");

                    b.Property<string>("StartDate")
                        .IsRequired();

                    b.Property<string>("StartTime")
                        .IsRequired();

                    b.Property<Guid?>("UserID");

                    b.HasKey("EventID");

                    b.HasIndex("RouteID");

                    b.HasIndex("UserID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("McWorld.Shared.Models.Registration", b =>
                {
                    b.Property<Guid?>("UserID");

                    b.Property<Guid?>("EventID");

                    b.HasKey("UserID", "EventID");

                    b.HasIndex("EventID");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("McWorld.Shared.Models.Route", b =>
                {
                    b.Property<Guid>("RouteID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Created")
                        .IsRequired();

                    b.Property<double>("Distance");

                    b.Property<bool>("Ferry");

                    b.Property<bool>("Motorway");

                    b.Property<bool>("Toll");

                    b.Property<Guid?>("UserID");

                    b.HasKey("RouteID");

                    b.HasIndex("UserID");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("McWorld.Shared.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Birthdate")
                        .IsRequired();

                    b.Property<string>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("McWorld.Shared.Models.Event", b =>
                {
                    b.HasOne("McWorld.Shared.Models.Route", "Route")
                        .WithMany("Events")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("McWorld.Shared.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("McWorld.Shared.Models.Registration", b =>
                {
                    b.HasOne("McWorld.Shared.Models.Event", "Event")
                        .WithMany("Registration")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("McWorld.Shared.Models.User", "User")
                        .WithMany("Registration")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("McWorld.Shared.Models.Route", b =>
                {
                    b.HasOne("McWorld.Shared.Models.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserID");

                    b.OwnsMany("McWorld.Shared.Models.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("Latitude");

                            b1.Property<string>("Longitude");

                            b1.Property<Guid>("RouteID");

                            b1.Property<string>("StreetName")
                                .IsRequired();

                            b1.Property<string>("StreetNumber")
                                .IsRequired();

                            b1.Property<int>("Zipcode");

                            b1.HasKey("AddressId");

                            b1.HasIndex("RouteID");

                            b1.ToTable("Address");

                            b1.HasOne("McWorld.Shared.Models.Route")
                                .WithMany("Addresses")
                                .HasForeignKey("RouteID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
